# Generated by Django 4.2.30 on 2026-04-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='current_price',
        ),
    ]
