# Generated by Django 4.2.30 on 2026-04-27 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfoliohistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioHistory',
        ),
    ]
